name: build test
on:
  workflow_call:
permissions:
  contents: read
jobs:
  build-test:
    runs-on: ubuntu-latest
    name: build test
    steps:
      - name: checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: setup bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
        with:
          bun-version: 'latest'
      - name: install dependencies
        run: bun i
      - name: build application
        run: bun bake
      - name: check build artifacts
        run: |
          test -f ./dist/index.html
          # hashed files
          [ -n "$(compgen -G "dist/editor*.js")" ] || exit 1
          [ -n "$(compgen -G "dist/stylez*.css")" ] || exit 1
          echo "Build successful"
      - name: upload build results as artifact
        if: success() && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: editor-build
          path: dist
          retention-days: 3
      - name: add artifact download info to summary
        run: |
          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "### :package: build Artifacts" >> $GITHUB_STEP_SUMMARY
          echo "- artifacts for this run are available under the **Artifacts** section of [this workflow run]($RUN_URL)." >> $GITHUB_STEP_SUMMARY
          echo "- or use the cli: \`gh run download ${{ github.run_id }} -n editor-build\`" >> $GITHUB_STEP_SUMMARY
